# ================================================================
# Pixel Bot - Installer Build Script (Inno Setup)
# ================================================================
# This script creates a professional Windows installer for Pixel Bot
# Requires: Inno Setup (https://jrsoftware.org/isinfo.php)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  Pixel Bot - Installer Build Script" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# ----------------------------------------------------------------
# Check Prerequisites
# ----------------------------------------------------------------
Write-Host "[1/4] Checking prerequisites..." -ForegroundColor Yellow

# Check if executable exists
if (-not (Test-Path "dist\PixelBot.exe")) {
    Write-Host "ERROR: PixelBot.exe not found!" -ForegroundColor Red
    Write-Host "Please build the executable first:" -ForegroundColor Red
    Write-Host "  .\build_standalone.ps1" -ForegroundColor Yellow
    exit 1
}
Write-Host "  [OK] PixelBot.exe found" -ForegroundColor Green

# Check if Inno Setup is installed
$innoSetupPaths = @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles(x86)}\Inno Setup 5\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 5\ISCC.exe"
)

$isccPath = $null
foreach ($path in $innoSetupPaths) {
    if (Test-Path $path) {
        $isccPath = $path
        break
    }
}

if (-not $isccPath) {
    Write-Host ""
    Write-Host "ERROR: Inno Setup not found!" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please install Inno Setup:" -ForegroundColor Yellow
    Write-Host "  1. Download from: https://jrsoftware.org/isdl.php" -ForegroundColor Gray
    Write-Host "  2. Install with default settings" -ForegroundColor Gray
    Write-Host "  3. Run this script again" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Alternative: Distribute PixelBot.exe directly (no installer needed)" -ForegroundColor Cyan
    exit 1
}

Write-Host "  [OK] Inno Setup found: $isccPath" -ForegroundColor Green

# ----------------------------------------------------------------
# Create Installer Script
# ----------------------------------------------------------------
Write-Host ""
Write-Host "[2/4] Creating installer script..." -ForegroundColor Yellow

$installerScript = @"
; Pixel Bot Installer Script
; Generated by build_installer.ps1

#define MyAppName "Pixel Bot"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Pixel Bot Team"
#define MyAppURL "https://github.com/yourusername/pixelbot"
#define MyAppExeName "PixelBot.exe"

[Setup]
AppId={{YOUR-UNIQUE-APP-ID-HERE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=installer
OutputBaseFilename=PixelBot_Setup_v{#MyAppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startmenuicon"; Description: "Create Start Menu icon"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\pixelbot_config.example.ini"; DestDir: "{app}"; Flags: ignoreversion; AfterInstall: RenameConfigFile
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion isreadme; DestName: "README.txt"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userstartmenu}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startmenuicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure RenameConfigFile();
begin
  // Don't overwrite existing config
  if not FileExists(ExpandConstant('{app}\pixelbot_config.ini')) then
  begin
    FileCopy(ExpandConstant('{app}\pixelbot_config.example.ini'), 
             ExpandConstant('{app}\pixelbot_config.ini'), False);
  end;
end;
"@

$installerScript | Out-File -FilePath "installer.iss" -Encoding UTF8 -Force
Write-Host "  [OK] installer.iss created" -ForegroundColor Green

# ----------------------------------------------------------------
# Build Installer
# ----------------------------------------------------------------
Write-Host ""
Write-Host "[3/4] Building installer..." -ForegroundColor Yellow
Write-Host "  This may take 1-2 minutes..." -ForegroundColor Gray
Write-Host ""

# Create installer output directory
New-Item -ItemType Directory -Path "installer" -Force | Out-Null

try {
    & $isccPath "installer.iss"
    
    if ($LASTEXITCODE -ne 0) {
        throw "Inno Setup compilation failed"
    }
} catch {
    Write-Host ""
    Write-Host "ERROR: Installer build failed!" -ForegroundColor Red
    Write-Host "Error: $_" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "  [OK] Installer build completed" -ForegroundColor Green

# ----------------------------------------------------------------
# Verify Output
# ----------------------------------------------------------------
Write-Host ""
Write-Host "[4/4] Verifying installer..." -ForegroundColor Yellow

$installerFile = Get-ChildItem -Path "installer\PixelBot_Setup_*.exe" | Select-Object -First 1

if (-not $installerFile) {
    Write-Host "ERROR: Installer file not created!" -ForegroundColor Red
    exit 1
}

$installerSize = $installerFile.Length / 1MB
Write-Host "  [OK] Installer created" -ForegroundColor Green
Write-Host "  [INFO] Size: $([math]::Round($installerSize, 2)) MB" -ForegroundColor Cyan

# ----------------------------------------------------------------
# Success Summary
# ----------------------------------------------------------------
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  INSTALLER BUILD SUCCESSFUL!" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Output:" -ForegroundColor Cyan
Write-Host "  Location:  $($installerFile.FullName)" -ForegroundColor White
Write-Host "  Size:      $([math]::Round($installerSize, 2)) MB" -ForegroundColor White
Write-Host ""
Write-Host "Features:" -ForegroundColor Cyan
Write-Host "  - Professional Windows installer" -ForegroundColor White
Write-Host "  - Program Files installation" -ForegroundColor White
Write-Host "  - Start Menu shortcuts" -ForegroundColor White
Write-Host "  - Optional desktop icon" -ForegroundColor White
Write-Host "  - Uninstaller included" -ForegroundColor White
Write-Host "  - Auto-creates config file" -ForegroundColor White
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Test the installer:" -ForegroundColor White
Write-Host "     Run: $($installerFile.Name)" -ForegroundColor Yellow
Write-Host ""
Write-Host "  2. Distribute:" -ForegroundColor White
Write-Host "     Share the installer file with users" -ForegroundColor Yellow
Write-Host "     They just run it and follow the wizard" -ForegroundColor Yellow
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""

